version: '3.9'

services:
  car-wars-builder:
    build:
      context: .
      dockerfile: Dockerfile
    image: car-wars-6e-builder:latest
    container_name: car-wars-6e-builder
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # Add other environment variables as needed
    # Uncomment and adjust if you need persistent storage
    # volumes:
    #   - ./public/uploads:/app/public/uploads
