version: '3.9'

services:
  car-wars-builder:
    image: car-wars-6e-builder:latest
    container_name: car-wars-6e-builder
    restart: unless-stopped
    user: "1000:1000"
    ports:
      - target: ${PORT}
        published: ${PORT}
        protocol: tcp
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SUB_DOMAIN}.rule=Host(`${SUB_DOMAIN}.nerps.net`)"
      - "traefik.http.routers.${SUB_DOMAIN}.entrypoints=proxy"
      - "traefik.http.services.${SUB_DOMAIN}.loadbalancer.server.port=${PORT}"
      - "traefik.http.routers.${SUB_DOMAIN}-secure.rule=Host(`${SUB_DOMAIN}.nerps.net`)"
      - "traefik.http.routers.${SUB_DOMAIN}-secure.tls=true"
      - "traefik.http.routers.${SUB_DOMAIN}.tls=true" # disable http
    environment:
      - NODE_ENV=production
    volumes:
      - type: bind
        source: /srv/carwars-6e-builder/public/uploads
        target: /app/public/uploads
      - type: bind
        source: /srv/carwars-6e-builder/public/stock-vehicles/
        target: /app/public/stock-vehicles
      - type: bind
        source: /srv/carwars-6e-builder/app/data
        target: /app/src/data
networks:
  proxy:
    external: true